name: Functional
description: Performs functional tests checks
runs:
  using: composite
  steps:
    - run:
        pnpm --filter anchors-test exec playwright install --with-deps chromium
      shell: sh
    - run: pnpm run build
      shell: sh
    - run: pnpm --filter anchors-test exec playwright test
      shell: sh
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: visual-snapshots-diff
        path: test-results
