name: Functional
description: Performs functional tests checks
runs:
  using: composite
  steps:
    - run: npx playwright install --with-deps chromium
      shell: sh
    - run: npm run build
      shell: sh
    - run: npm run playwright
      shell: sh
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: visual-snapshots-diff
        path: test-results
