name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  type-checks:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm run lint
        shell: sh
      - run: pnpm run typecheck
        shell: sh

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm --filter '@folz/anchors' --filter '@folz/anchors-react' build
        shell: sh
      - run: pnpm --filter '@folz/anchors' --filter '@folz/anchors-react' test
        shell: sh
#  functional-tests:
#    name: Functional tests
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        shardIndex: [1, 2, 3]
#        shardTotal: [3]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/setup
#      - run:
#          pnpm --filter '@folz/anchors-test' exec playwright install --with-deps
#          chromium
#        shell: sh
#      - run: pnpm --filter '@folz/anchors' --filter '@folz/anchors-react' build
#        shell: sh
#      - run:
#          pnpm --filter '@folz/anchors-test' exec playwright test --shard=${{
#          matrix.shardIndex }}/${{ matrix.shardTotal }} --workers=1
#        shell: sh
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: visual-snapshots-diff
#          path: test-results
